# Generated by Django 5.1.7 on 2025-04-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='original_image',
            field=models.ImageField(upload_to='original/', verbose_name='Original Image'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/', verbose_name='Processed Image'),
        ),
    ]
